name: Deploy
on:
  push:
    branches:
      - main

jobs:
  buildAndDeploy:
    name: Build and Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout & Build
        uses: actions/checkout@v4

      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci && npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: 'gravitycloud/gravity-ci-cd-agent:latest'
          platforms: linux/arm64
